# Generated by Django 5.1.6 on 2025-02-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
