# Generated by Django 5.1.6 on 2025-02-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='payed',
            new_name='pay',
        ),
    ]
